export {
  boundsFromPoints,
  pointToSegmentDistanceSquared,
  segmentCrossesBounds,
  segmentIntersection,
  segmentMidpoint,
  segmentNearPoint,
  segmentWithinBounds,
  squaredDistance,
  type CadBounds,
  type CadSegment,
} from './cad-segment-geometry'
export {
  arcBounds,
  arcContainsAngle,
  arcEndpoints,
  arcMidpoint,
  arcPointAt,
  arcQuadrants,
  arcThroughPoints,
  flattenCadArc,
  isFullCircle,
  pointToArcDistanceSquared,
  type CadArcShape,
} from './cad-arc-geometry'
export {
  arcCurve,
  geometryBounds,
  geometryCrossesBounds,
  geometryNearPoint,
  geometryWithinBounds,
  pointToGeometryDistanceSquared,
  segmentCurve,
  textGeometry,
  type CadArcCurve,
  type CadCurve,
  type CadGeometry,
  type CadSegmentCurve,
  type CadTextGeometry,
} from './cad-curve'
export {
  CAD_TEXT_ADVANCE_RATIO,
  CAD_TEXT_ASCENT_RATIO,
  CAD_TEXT_DESCENT_RATIO,
  cadTextBounds,
  cadTextCorners,
  cadTextWidth,
  pointToTextDistanceSquared,
  type CadTextAlign,
  type CadTextShape,
} from './cad-text-geometry'
export {
  cadPolylineSegments,
  isDegenerateCadPolyline,
} from './cad-polyline-geometry'
