/**
 * 无 React、无 DOM 的 CAD 文档协议与资源 Store。
 *
 * @remarks
 * `CadDocument` 复用 ComposeDocument 的 ECS 底座——Entity 结构、Patch 代数、事务运行时、
 * Undo/Redo 与序列化全部共用，差异只在校验器与 Component 词汇。因此这里没有第二套事务实现。
 *
 * CAD 是**无限图纸**：文档不带任何画布或输出尺寸，也没有 Frame，因此不受
 * 「`Frame.size` 是尺寸唯一事实来源」这条 ComposeDocument 不变量约束。单位固定 `px`。
 *
 * @packageDocumentation
 */

export {
  CAD_COMPONENT_KEYS,
  CAD_DEFAULT_LAYER_ID,
  createCadArcEntity,
  createCadLineEntity,
  createCadPolylineEntity,
  createCadTextEntity,
  createCadWireEntity,
  createEmptyCadDocument,
  getCadArc,
  getCadInsert,
  getCadLine,
  getCadPlacement,
  getCadPolyline,
  getCadText,
  getCadWire,
  validateCadDocument,
  type CadArc,
  type CadBlockDefinition,
  type CadDocument,
  type CadDocumentIssue,
  type CadDocumentIssueCode,
  type CadInsert,
  type CadLayer,
  type CadLine,
  type CadFreeEndpoint,
  type CadPlacement,
  type CadPoint,
  type CadPort,
  type CadPolyline,
  type CadPortEndpoint,
  type CadText,
  type CadWire,
  type CadWireEndpoint,
} from './document'
export { previewCadTranslate, translateCadEntity } from './transform'
export {
  collectCadVisibleGeometry,
  createCadInsert,
  inverseCadBlockPoint,
  transformCadBlockPoint,
  type CadVisibleGeometry,
} from './block'
export {
  arcMidpoint,
  arcQuadrants,
  arcThroughPoints,
  CAD_TEXT_ADVANCE_RATIO,
  CAD_TEXT_ASCENT_RATIO,
  CAD_TEXT_DESCENT_RATIO,
  cadPolylineSegments,
  cadTextCorners,
  cadTextWidth,
  isDegenerateCadPolyline,
  geometryBounds,
  isFullCircle,
  type CadArcCurve,
  type CadArcShape,
  type CadCurve,
  type CadGeometry,
  type CadSegmentCurve,
  type CadTextAlign,
  type CadTextGeometry,
  type CadTextShape,
} from './geometry'
export {
  collectCadInsertPositions,
  collectCadInstancePorts,
  resolveCadPortPoint,
  resolveCadWireEndpoint,
  resolveCadWireSegment,
  type CadInstancePort,
} from './connection'
export {
  CAD_SNAP_MODES,
  findCadSnap,
  type CadSnapCandidate,
  type CadSnapMode,
} from './snap'
export {
  parseCadCoordinate,
  resolveCadPoint,
  type CadCoordinateFailure,
  type CadInputPoint,
  type CadGridSettings,
  type CadPointContext,
  type CadPointSource,
  type ParseCadCoordinateResult,
} from './point-input'
export {
  CAD_COMMAND_TYPES,
  createCadArcCommand,
  createCadArcSession,
  createCadBlockCommand,
  createCadBlockSession,
  createCadCircleCommand,
  createCadCircleSession,
  createCadCommandHandlers,
  createCadCopyCommand,
  createCadEraseCommand,
  createCadEraseSession,
  createCadInsertCommand,
  createCadInsertSession,
  createCadLineCommand,
  createCadMoveCommand,
  createCadLineSession,
  CAD_DEFAULT_TEXT_HEIGHT,
  createCadPolylineCommand,
  createCadPolylineSession,
  createCadPortCommand,
  createCadPortSession,
  createCadRectangleCommand,
  createCadRectangleSession,
  createCadTextCommand,
  createCadTextSession,
  createCadWireCommand,
  createCadWireSession,
  type CadAddBlockPortPayload,
  type CadAddEntityPayload,
  type CadAddWirePayload,
  type CadCreateBlockPayload,
  type CadCommandContext,
  type CadCommandEffect,
  type CadCommandMessages,
  type CadRemoveEntityPayload,
} from './command'
export {
  applyCadSelection,
  cadSelectionBoundsFromDrag,
  cadSelectionModeFromDrag,
  findCadEntitiesInBounds,
  findCadHit,
  pruneCadSelection,
  type CadSelectionBounds,
  type CadSelectionChange,
  type CadSelectionMode,
} from './selection'
export {
  CAD_COMMAND_POINT_PLUGIN_ID,
  CAD_GESTURE_PRIORITY,
  CAD_MARQUEE_PLUGIN_ID,
  CAD_MOVE_PLUGIN_ID,
  CAD_SELECT_PLUGIN_ID,
  createCadCommandPointPlugin,
  createCadInteractionPlugins,
  createCadMarqueePlugin,
  createCadPluginRegistry,
  createCadSceneIndex,
  createCadMovePlugin,
  createCadSelectPlugin,
  createCadSessionArbiter,
  type CadClaimResult,
  type CadInteractionContext,
  type CadInteractionEffect,
  type CadInteractionEvent,
  type CadInteractionPlugin,
  type CadInteractionSnapshot,
  type CadKernelProfile,
  type CadPluginContext,
  type CadPluginRegistry,
  type CadPointerDownEvent,
  type CadPointerModifiers,
  type CadSceneIndex,
  type CadSession,
  type CadSessionArbiter,
} from './interaction'
export {
  importDxfDocument,
  type DxfDiagnostic,
  type DxfDiagnosticCode,
  type DxfImportResult,
} from './dxf'
export {
  COMPOSE_CAD_FILE_SUFFIX,
  COMPOSE_CAD_MEDIA_TYPE,
  composeCadDisplayName,
  composeCadFileName,
  createComposeCadStore,
  isComposeCadFileName,
  parseComposeCadDocument,
  serializeComposeCadDocument,
  type ComposeCadCatalog,
  type ComposeCadDescriptor,
  type ComposeCadSnapshot,
  type ComposeCadStore,
  type ComposeCadStoreEvent,
  type CreateComposeCadInput,
  type ParseComposeCadResult,
} from './store'

/** `@compose-ui/cad` 的稳定包标识。 @public */
export const COMPOSE_UI_CAD_PACKAGE = '@compose-ui/cad' as const
