/** Entity Registry 领域协议与工厂的功能入口。 */
export { createComposeEntityRegistry } from './registry'
export {
  resolveComposeRendererRuntimeProps,
} from './runtime-props'
export type { ComposeRendererRuntimePropsResult } from './runtime-props'
export {
  ComposeEntityRegistryError,
  type ComposeCapabilityAvailability,
  type ComposeCapabilityDefinition,
  type ComposeCapabilityIssue,
  type ComposeCapabilityPlanResult,
  type ComposeComponentDefinition,
  type ComposeComponentInspectorProps,
  type ComposeEntityAssetDropDefinition,
  type ComposeEntityAssetDropInput,
  type ComposeEntityInspectorContext,
  type ComposeMissingComponentInspectorDefinition,
  type ComposeMissingComponentInspectorProps,
  type ComposeEntityPreset,
  type ComposeNodeEditPort,
  type ComposePaintEditPort,
  type ComposeEntityRegistry,
  type ComposeEntityRegistryOptions,
  type ComposeEntitySeed,
  type ComposeEntitySeedError,
  type ComposeEntitySeedResult,
  type ComposeRendererDefinition,
  type ComposeRendererBindingDiagnostic,
  type ComposeRendererPropCategory,
  type ComposeRendererPropContract,
  type ComposeRendererMeasurementDefinition,
  type ComposeRendererMeasurementSubscriptionInput,
  type ComposeRendererMeasureInput,
  type ComposeRendererPrepareInput,
  type ComposeRendererInspectorProps,
  type ComposeRendererInspectorBindingPort,
  type ComposeRendererInspectorBindingState,
  type ComposeRendererInspectorBindingVariable,
  type ComposeRendererProps,
  type ComposeRendererTextEditing,
  type ComposeRuntimeProps,
} from './types'
