/**
 * 提供 React 与 DOM 无关的 Stage 坐标、空间命令与交互运行时。
 *
 * @packageDocumentation
 */

/** 坐标、矩阵、网格点阵与吸附。 */
export {
  ROTATION_SNAP_DEGREES,
  applyMatrix,
  COMPOSE_LATTICE_FADE_START,
  COMPOSE_LATTICE_MIN_FULL_SPACING,
  composeLatticeDetailFade,
  composeLatticeStackedAlpha,
  createAxisLattice,
  createRulerTicks,
  decomposeMatrix,
  expandScrollRange,
  getEntityParentId,
  getEntityWorldBounds,
  getEntityWorldMatrix,
  invertMatrix,
  latticeLineBand,
  latticeLinePosition,
  listFrameWorldGuides,
  matrixFromTransform,
  multiplyMatrices,
  pointOnRotationRay,
  rectContains,
  rectMappingMatrix,
  rectsIntersect,
  resizeBounds,
  resizeReadoutPoints,
  STAGE_GIZMO_ARROW_LENGTH,
  STAGE_GIZMO_MOVE_HIT_START,
  STAGE_GIZMO_MOVE_HIT_WIDTH,
  STAGE_GIZMO_ARROW_WIDTH,
  STAGE_GIZMO_AXIS_LENGTH,
  STAGE_GIZMO_CENTER_RADIUS,
  STAGE_GIZMO_RING_HIT_WIDTH,
  STAGE_GIZMO_RING_RADIUS,
  STAGE_GIZMO_SCALE_DISTANCE,
  STAGE_GIZMO_SCALE_HIT_SIZE,
  STAGE_GIZMO_SCALE_SIZE,
  gizmoScaleHandle,
  transformGizmoGeometry,
  resolveTargetFrameId,
  rotationFromPointer,
  rotationMatrixAround,
  screenToWorld,
  STAGE_ZOOM_RANGE,
  scrollAxisToViewport,
  snapResizePoint,
  snapTranslation,
  stageCurveToParent,
  stageCurveToSpace,
  stagePointToParent,
  snapValueToGrid,
  toComposeTransform,
  toFrameGuidePosition,
  toStageTransform,
  translationMatrix,
  unionRects,
  viewportToScrollAxes,
  worldToScreen,
  zoomViewportAt,
  type FrameOriginResolver,
  type ResizeHandle,
  type StageAxisLattice,
  type StageGuide,
  type StageLatticeBand,
  type StageMatrix,
  type StagePoint,
  type StageRect,
  type StageRulerTick,
  type StageScrollAxis,
  type StageTransform,
  type StageTransformGizmoAxis,
  type StageTransformGizmoGeometry,
  type StageViewport,
} from './geometry'

/** 场景索引、拖放落点与框选。 */
export {
  createStageSceneIndex,
  resolveMarqueeHitTest,
  resolveMarqueeSelection,
  resolveStageDropIndicator,
  resolveStageDropTarget,
  resolveStageGridCell,
  resolveStageGridContext,
  solveStageGrid,
  type StageDropIndicator,
  type StageDropTarget,
  type StageGridContext,
  type StageMarqueeCombine,
  type StageMarqueeDirection,
  type StageMarqueeHitTest,
  type StageMarqueeQuery,
  type StageSceneIndex,
} from './hit-testing'

/** 视口裁剪：量化窗口与可见集；只供渲染使用，不参与任何命中或几何查询。 */
export {
  resolveStageCullingExemptIds,
  resolveStageCullingWindow,
  resolveStageDetailCulledIds,
  resolveStageVisibleEntityIds,
  type StageCullingExemptions,
  type StageCullingWindow,
  type StageLegibleSize,
} from './culling'

/** 手势的预览几何与提交规划。 */
export {
  planStageAlignment,
  planStageMirror,
  planTransformCommit,
  resolveTransformGizmoTarget,
  resolveTransformTargets,
  transformedResizeSelection,
  transformedSelection,
  stageAlignmentMinimum,
  STAGE_ALIGN_MINIMUM,
  STAGE_DISTRIBUTE_MINIMUM,
  type StageAlignmentMode,
  type StageFinishedTransform,
  type StageMirrorQuery,
  type StageMoveAxis,
  type StageTransformGizmoTarget,
  type StageTransformKind,
  type StageTransformTargets,
} from './gesture-planning'

/** 空间命令的规划与事务标签。 */
export {
  clampBoundsIntoFrame,
  createComponentExtractionPlan,
  createDuplicateCommand,
  createEntityClipboard,
  createGroupCommand,
  createLayerOrderCommand,
  createPasteFromClipboard,
  createReparentCommand,
  createReplaceSelectionWithEntityCommand,
  createStageDeleteEntitiesCommand,
  createUngroupCommand,
  describeEntityCreation,
  describeEntityTargets,
  describeTransform,
  getGroupCommandAvailability,
  getLayerOrderCommandAvailability,
  getUngroupCommandAvailability,
  isComposeContainerEntity,
  isInvalidCutInsertion,
  normalizeClipboardEntityIds,
  orientStageWireVertices,
  planStageJunctionCleanup,
  planStageWireCut,
  planStageCurveReplacement,
  planStageTrim,
  resolveStageHatchRegion,
  resolveStageTrailTargets,
  resolveStageTrimPiece,
  stageBoxCurve,
  stageCurveMatchesEntity,
  stageWorldOutline,
  stageWorldShapes,
  stageCurveParentGeometry,
  type StageCurveReplacementOptions,
  type StageCurveReplacementPlan,
  type StageHatchOptions,
  type StageHatchRejection,
  type StageHatchResolution,
  type StageTrimCut,
  type StageTrimOptions,
  type StageWorldShape,
  type StageTrimPiece,
  type StageTrimPlan,
  type StageTrimRejection,
  type StageTrimResolution,
  planStageWireMerge,
  stageWireParentVertices,
  resolveNextScenePlacement,
  resolveSuggestedEntityInsertion,
  type ComposeClipboardPastePlan,
  type ComposeComponentExtractionPlan,
  type ComposeComponentExtractionResult,
  type ComposeComponentExtractionUnavailableReason,
  type ComposeDuplicateInsertion,
  type ComposeEntityClipboard,
  type ComposeEntityInsertion,
  type ComposeLayerOrderOperation,
  type ComposeStructureCommandAvailability,
  type StageDeleteEntitiesOptions,
  type StageJunctionPredicate,
  type StageWireBranch,
  type StageWireCutOptions,
  type StageWireCutPlan,
  type StageWireMergePlan,
} from './commands'

/** 交互运行时入口。 */
export {
  createStageInteractionController,
  type StageDrawingPreview,
  type StageDrawnEntity,
  type StageEditablePath,
  type StageEditablePathVertex,
  type StageExternalAssetItem,
  type StageExternalDragItem,
  type StageInteractionContext,
  type StageInteractionController,
  type StageInteractionEffect,
  type StageInteractionEvent,
  type StageInteractionHit,
  type StageInteractionModifiers,
  type StageInteractionPhase,
  type StageInteractionSnapshot,
  type StageInteractionSurfacePort,
  type StageInteractionTool,
  type StagePaintEditing,
  type StagePaintHandle,
  type StagePaintHandleKind,
  type StagePaintSamplePreview,
  type StagePaintSampling,
  type StagePathEditing,
  type StagePathHandleKind,
  type StagePreviewGuide,
  type StageTextEditing,
} from './interaction-controller'

/** 手势仲裁与插件协议。 */
export {
  STAGE_EXTRACTED_PLUGIN_FACTORIES,
  STAGE_GESTURE_PRIORITY,
  captureStageSpatialBaseline,
  createStagePluginRegistry,
  createStageSessionArbiter,
  type StageArbiterBeginResult,
  type StageClaimResult,
  type StageGesturePriorityEntry,
  type StageInteractionPlugin,
  type StagePluginContext,
  type StagePluginRegistry,
  type StagePointerDownEvent,
  type StageSession,
  type StageSessionArbiter,
  type StageSpatialBaselineCheck,
} from './interaction-kernel'

/** `@compose-ui/stage-engine` 的稳定包标识。 @public */
export const COMPOSE_UI_STAGE_ENGINE_PACKAGE = '@compose-ui/stage-engine' as const
export {
  COMPOSE_POLYGON_DEFAULT_SIDES,
  COMPOSE_POLYGON_MAX_SIDES,
  COMPOSE_POLYGON_MIN_SIDES,
  createStageCopyCommand,
  createStageCopySession,
  createStageDraftingCommands,
  createStageDraftingPickPlugin,
  createStageDraftingPointPlugin,
  createStageEraseCommand,
  createStageTrimCommand,
  createStageHatchCommand,
  createStageHatchSession,
  createStageTrimSession,
  createStageEraseSession,
  createStageGripSession,
  createStageLineCommand,
  createStageLineSession,
  createStageMoveCommand,
  createStageMoveSession,
  createStagePolygonCommand,
  createStagePolygonSession,
  createStageVertexCommand,
  createStageVertexSession,
  planStageDraftingEdits,
  STAGE_DRAFTING_PICK_PLUGIN_ID,
  STAGE_DRAFTING_POINT_PLUGIN_ID,
} from './drafting'
export type {
  StageDraftingContext,
  StageDraftingEditQuery,
  StageDraftingEffect,
  StageDraftingGripEdit,
  StageDraftingMessages,
  StageDraftingSegment,
  StageDraftingTranslation,
  StageGripTarget,
} from './drafting'
export {
  collectStageRevealedPorts,
  collectStageWireEnds,
  findStageFeaturePoint,
  resolveStageClickSelection,
  resolveStageGroupExit,
  resolveStageGroupHit,
  resolveStageMarqueeCombine,
} from './hit-testing'
export type {
  StageFeaturePoint,
  StageFeatureSnapMode,
  StageGroupHitQuery,
  StageGroupHitResolution,
  StageWirePredicate,
  StageRevealedPorts,
  StageSelectionMode,
  StageWireEnd,
} from './hit-testing'
export {
  applyStageCurveCorner,
  applyStageCurveGrip,
  deleteStageCurveVertex,
  insertStageCurveVertex,
  stageCurveBoxGeometry,
  stageCurveCorners,
  isStageInteriorVertexGrip,
  stageCurveGripNeighbor,
  stageCurveGrips,
  stageCurveLocalPoint,
  stageCurveOutline,
} from './geometry-editing'
export type {
  StageCurveCorner,
  StageCurveGeometrySource,
  StageCurveGrip,
  StageCurveGripRole,
  StageVertexDelete,
  StageVertexDeleteOptions,
  StageVertexEdit,
  StageVertexEditRejection,
} from './geometry-editing'
