/**
 * 提供 React 与 DOM 无关的 Stage 坐标、空间命令与交互运行时。
 *
 * @packageDocumentation
 */

/** 坐标、矩阵、网格点阵与吸附。 */
export {
  ROTATION_SNAP_DEGREES,
  applyMatrix,
  createAxisLattice,
  createRulerTicks,
  decomposeMatrix,
  expandScrollRange,
  getEntityParentId,
  getEntityWorldBounds,
  getEntityWorldMatrix,
  invertMatrix,
  latticeLineBand,
  latticeLinePosition,
  listFrameWorldGuides,
  matrixFromTransform,
  multiplyMatrices,
  pointOnRotationRay,
  rectContains,
  rectMappingMatrix,
  rectsIntersect,
  resizeBounds,
  resolveTargetFrameId,
  rotationFromPointer,
  rotationMatrixAround,
  screenToWorld,
  STAGE_ZOOM_RANGE,
  scrollAxisToViewport,
  snapResizePoint,
  snapTranslation,
  snapValueToGrid,
  toComposeTransform,
  toFrameGuidePosition,
  toStageTransform,
  translationMatrix,
  unionRects,
  viewportToScrollAxes,
  worldToScreen,
  zoomViewportAt,
  type FrameOriginResolver,
  type ResizeHandle,
  type StageAxisLattice,
  type StageGuide,
  type StageLatticeBand,
  type StageMatrix,
  type StagePoint,
  type StageRect,
  type StageRulerTick,
  type StageScrollAxis,
  type StageTransform,
  type StageViewport,
} from './geometry'

/** 场景索引、拖放落点与框选。 */
export {
  DEFAULT_STAGE_MARQUEE_MODE,
  createStageSceneIndex,
  resolveMarqueeHitTest,
  resolveMarqueeSelection,
  resolveStageDropIndicator,
  resolveStageDropTarget,
  type StageDropIndicator,
  type StageDropTarget,
  type StageMarqueeCombine,
  type StageMarqueeDirection,
  type StageMarqueeMode,
  type StageMarqueeQuery,
  type StageSceneIndex,
} from './hit-testing'

/** 手势的预览几何与提交规划。 */
export {
  planTransformCommit,
  resolveTransformTargets,
  transformedResizeSelection,
  transformedSelection,
  type StageFinishedTransform,
  type StageTransformKind,
  type StageTransformTargets,
} from './gesture-planning'

/** 空间命令的规划与事务标签。 */
export {
  clampBoundsIntoFrame,
  createComponentExtractionPlan,
  createDuplicateCommand,
  createEntityClipboard,
  createGroupCommand,
  createLayerOrderCommand,
  createPasteFromClipboard,
  createReparentCommand,
  createReplaceSelectionWithEntityCommand,
  createUngroupCommand,
  describeEntityCreation,
  describeEntityTargets,
  describeTransform,
  getGroupCommandAvailability,
  getLayerOrderCommandAvailability,
  getUngroupCommandAvailability,
  isComposeContainerEntity,
  isInvalidCutInsertion,
  normalizeClipboardEntityIds,
  resolveNextScenePlacement,
  resolveSuggestedEntityInsertion,
  type ComposeClipboardPastePlan,
  type ComposeComponentExtractionPlan,
  type ComposeComponentExtractionResult,
  type ComposeComponentExtractionUnavailableReason,
  type ComposeDuplicateInsertion,
  type ComposeEntityClipboard,
  type ComposeEntityInsertion,
  type ComposeLayerOrderOperation,
  type ComposeStructureCommandAvailability,
} from './commands'

/** 交互运行时入口。 */
export {
  createStageInteractionController,
  type StageDrawingPreview,
  type StageDrawnEntity,
  type StageEditablePath,
  type StageEditablePathVertex,
  type StageExternalAssetItem,
  type StageExternalDragItem,
  type StageInteractionContext,
  type StageInteractionController,
  type StageInteractionEffect,
  type StageInteractionEvent,
  type StageInteractionHit,
  type StageInteractionModifiers,
  type StageInteractionPhase,
  type StageInteractionSnapshot,
  type StageInteractionSurfacePort,
  type StageInteractionTool,
  type StagePaintEditing,
  type StagePaintHandle,
  type StagePaintHandleKind,
  type StagePaintSamplePreview,
  type StagePaintSampling,
  type StagePathEditing,
  type StagePathHandleKind,
  type StagePreviewGuide,
  type StageSegmentPreview,
  type StageTextEditing,
} from './interaction-controller'

/** 手势仲裁与插件协议。 */
export {
  STAGE_EXTRACTED_PLUGIN_FACTORIES,
  STAGE_GESTURE_PRIORITY,
  captureStageSpatialBaseline,
  createStagePluginRegistry,
  createStageSessionArbiter,
  type StageArbiterBeginResult,
  type StageClaimResult,
  type StageGesturePriorityEntry,
  type StageInteractionPlugin,
  type StagePluginContext,
  type StagePluginRegistry,
  type StagePointerDownEvent,
  type StageSession,
  type StageSessionArbiter,
  type StageSpatialBaselineCheck,
} from './interaction-kernel'

/** `@compose-ui/stage-engine` 的稳定包标识。 @public */
export const COMPOSE_UI_STAGE_ENGINE_PACKAGE = '@compose-ui/stage-engine' as const
